# Input related configs

# input file path.
# Override the file path to provide a custom input.
populationData: src/main/resources/sample_input.csv
types: [ENGINEER, QA, BA]
attributeCount: 3
# CSV header mapping of the input file.
headerMapping:
  id: INDEX
  name: NAME
  type: TYPE
  attribute1: EXPERIENCE
  attribute2: PERFORMANCE
  attribute3: PROFESSIONAL

# Exclude !attributes
excluded:

# Application related configurations
mutationRate: 0.05
crossoverRate: 0.6
generations: 1000
initialPopulationSize: 10