# Input related configs

# input file path.
# Override the file path to provide a custom input.
populationData: src/main/resources/sample_input.csv
employeeTypes: [ENGINEER, QA, BA]
attributeCount: 3
# CSV header mapping of the input file.
headerMapping:
  id: INDEX
  name: NAME
  type: TYPE
  attribute1: EXPERIENCE
  attribute2: PERFORMANCE
  attribute3: PROFESSIONAL_QUALIFICATIONS

# Attribute ranges
# Specify ranges as a list [lowest, step size, highest]
attributeRanges:
  attribute1: [1, 1, 5]
  attribute2: [1, 1, 5]
  attribute3: [1, 1, 5]

# Exclude !attributes
excluded:

# Application related configurations
mutationRate: 0.001
generations: 1000
initialPopulationSize: 10