# Input related configs

# input file path.
# Override the file path to provide a custom input.
populationData: samples/sample_input.csv

# CSV header mapping of the input file.
headerMapping:
  id: INDEX
  name: NAME
  type: TYPE
  attribute1: EXPERIENCE
  attribute2: PERFORMANCE
  attribute3: PROFESSIONAL_QUALIFICATIONS

# Exclude !attributes
excluded:
  - NAME
  - INDEX
  - TYPE

# Application related configurations
mutationRate: 0.001
generations: 1000
initialPopulationSize: 10